import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Content from "~/components/Content";
import Article from "~/components/Content";
import Header from "~/components/Header";

import { api } from "~/utils/api";


export default function Home() {

  return (
    <>
      <Head>
        <title>Newspaper Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-custom bg-amber-50 w-screen h-screen">
        <Header></Header>
        <div className="flex flex-col items-center h-full mx-10 border-neutral-700 border-t-2">
        <Content></Content>
        </div>
        
      </main>
      
    </>
  );
}

