import Head from "next/head";
import Content from "~/components/Content";
import Header from "~/components/Header";
import { signIn, useSession } from "next-auth/react";
import { AiFillGoogleCircle, AiFillGithub } from "react-icons/ai";

export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Newspaper Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="./favicon.png" />
      </Head>

      {sessionData?.user ? (
        <>
          <main className="h-screen w-screen overflow-auto bg-bodyColor font-custom">
            <Header></Header>
            <div className="mx-10 flex flex-col items-center border-t-2 border-neutral-700">
              <Content></Content>
            </div>
          </main>
        </>
      ) : (
        <main className="flex h-screen w-screen flex-col items-center justify-center gap-3 overflow-auto bg-amber-50 font-custom">
          <h1 className="text-3xl font-black">NewsPaper Notes! 📰</h1>
          <div className="flex h-fit w-fit flex-col items-center justify-between gap-2 rounded-md border-2 border-neutral-600 bg-stone-200 p-10">
            <h2 className="text-3xl font-bold">Get Started!</h2>
            <p className="text-xl">
              Made by{" "}
              <a className="underline" href="https://pranavtech.dev/">
                Pranav
              </a>
            </p>
            <h2 className="text-2xl font-bold">Sign in with:</h2>
            <div className="grid grid-cols-2 items-center gap-3">
              <div className="flex flex-col items-center p-3 font-semibold">
                Google:
                <button onClick={() => void signIn("google")}>
                  <AiFillGoogleCircle
                    className="hover:cursor-pointer"
                    size={40}
                  ></AiFillGoogleCircle>
                </button>
              </div>
              <div className="flex flex-col items-center p-3 font-semibold">
                Github:
                <button onClick={() => void signIn("github")}>
                  <AiFillGithub
                    className="hover:cursor-pointer"
                    size={40}
                  ></AiFillGithub>
                </button>
              </div>
            </div>
          </div>
          <footer>Built with NextJS</footer>
        </main>
      )}
    </>
  );
}
